### ISSUE TITLE
Folia下Warden消失时有概率触发ConcurrentModificationException

### ISSUE THREAD

**Issue by MATRIX-feather** [MATRIX-feather/bonemeal#1]
```
[23:19:29 ERROR]: Could not pass event EntityRemoveFromWorldEvent to FeatherExperience v2024.503.0
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116) ~[?:?]
        at com.google.common.collect.Collections2$TransformedCollection.forEach(Collections2.java:301) ~[guava-32.1.2-jre.jar:?]
        at xyz.nifeather.fexp.features.bossbar.BossbarHolder.dispose(BossbarHolder.java:122) ~[feather-experience-2024.503.0.jar:?]
        at xyz.nifeather.fexp.features.bossbar.BossbarManager.drop(BossbarManager.java:36) ~[feather-experience-2024.503.0.jar:?]
        at xyz.nifeather.fexp.features.bossbar.BossbarListener.onEntityRemove(BossbarListener.java:28) ~[feather-experience-2024.503.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor253.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:git-Luminol-"7293124"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:3121) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2952) ~[?:?]
        at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:304) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:916) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5770) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at net.minecraft.world.entity.Entity.remove(Entity.java:714) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:780) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tickDeath(LivingEntity.java:648) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:497) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:388) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:827) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3092) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:461) ~[?:?]
        at net.minecraft.world.entity.monster.warden.Warden.tick(Warden.java:246) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1560) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1369) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:1011) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:620) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:989) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1845) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"7293124"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by MATRIX-feather** [comment]
可以通过关闭监守者Boss条来缓解此问题。
游戏内禁用方法：`/fexp option bossbar.warden false`
